[project]
name = "options-income-advisor-agent"
version = "0.1.0"
description = "LangGraph agent for options income porfolio analysis"
authors = [
    {name = "Lisandro Navarra",email = "lisandro.navarra@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<4.0.0"
dependencies = [
    "langgraph (>=1.1.10,<2.0.0)",
    "langchain-anthropic (>=1.4.2,<2.0.0)",
    "langsmith (>=0.7.38,<0.8.0)",
    "langchain-core (>=1.3.2,<2.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "pandas (>=3.0.2,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)",
    "ruff (>=0.15.12,<0.16.0)",
    "ipykernel (>=7.2.0,<8.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)"
]

[tool.poetry]
name = "options-income-advisor-agent"
version = "0.1.0"
description = "LangGraph agent for options income portfolio analysis"
package-mode = false    # ← add this line